# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-24 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='First name')),
                ('last_name', models.CharField(max_length=25, verbose_name='Last name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'emma_profile_pictures', verbose_name='Profile picture')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('description', models.TextField(verbose_name='Description')),
                ('familiar_structure', models.TextField(verbose_name='Familiar Structure')),
                ('personality', models.TextField(verbose_name='Personality')),
                ('is_candidate', models.BooleanField(default=True, verbose_name='Candidate')),
            ],
            options={
                'verbose_name': 'Adult',
                'verbose_name_plural': 'Adults',
            },
        ),
        migrations.CreateModel(
            name='AdultAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_name', models.CharField(max_length=50, verbose_name='Adult Name')),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('outdoor_number', models.CharField(max_length=25, verbose_name='Outdoor Number')),
                ('interior_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Interior Number')),
                ('colony', models.CharField(max_length=50, verbose_name='Colony')),
                ('postal_code', models.PositiveIntegerField(verbose_name='Postal Code')),
                ('municipality', models.CharField(max_length=50, verbose_name='Municipality')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('reference', models.TextField(verbose_name='Reference')),
                ('google_maps_link', models.TextField(verbose_name='Google Maps Link')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='AdultHobbie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbie', models.TextField(verbose_name='Hobbie')),
                ('adult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adults.Adult', verbose_name='Adult')),
            ],
            options={
                'verbose_name': 'Adult Hobbie',
                'verbose_name_plural': 'Adult Hobbie',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25, verbose_name='First name')),
                ('relation', models.CharField(max_length=25, verbose_name='Relation')),
                ('cell_phone', models.CharField(max_length=25, verbose_name='Cell Phone')),
                ('home_phone', models.CharField(max_length=25, verbose_name='Home Phone')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
            },
        ),
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_name', models.CharField(max_length=50, verbose_name='Adult Full Name')),
                ('blood_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='Blood Type')),
                ('hospital_preferably', models.CharField(blank=True, max_length=25, null=True, verbose_name='Hospital Preferably')),
                ('knows_pda', models.BooleanField(default=False, verbose_name='Knows PDA')),
                ('exercise_pda', models.BooleanField(default=False, verbose_name='Exercise PDA')),
                ('has_medical_insurance', models.BooleanField(default=False, verbose_name='Has Medical Insurance')),
                ('insurance_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Insurance Company')),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Policy Number')),
                ('policy_expiration_date', models.DateField(blank=True, null=True, verbose_name='Policy Experation Date')),
                ('has_social_security', models.BooleanField(default=True, verbose_name='Has Social Security')),
                ('social_security_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Social Security Number')),
                ('diseases', models.TextField(blank=True, null=True, verbose_name='Diseases')),
                ('current_medications', models.TextField(blank=True, null=True, verbose_name='Current Medications')),
                ('drug_allergy', models.TextField(blank=True, null=True, verbose_name='Drug Allergy')),
                ('food_allergy', models.TextField(blank=True, null=True, verbose_name='Food Allergy')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor', verbose_name='Doctor')),
                ('emergency_contact_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact_1', to='adults.EmergencyContact', verbose_name=b'Emergency Contact #1')),
                ('emergency_contact_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact_2', to='adults.EmergencyContact', verbose_name=b'Emergency Contact #2')),
            ],
            options={
                'verbose_name': 'Medical Information',
                'verbose_name_plural': 'Medical Information',
            },
        ),
        migrations.AddField(
            model_name='adult',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adults.AdultAddress', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='adult',
            name='medical_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adults.MedicalInfo', verbose_name='Medical Information'),
        ),
    ]
