# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='First name')),
                ('last_name', models.CharField(max_length=25, verbose_name='Last name')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('marital_status', models.CharField(choices=[(b'married', 'Married'), (b'widowed', 'Widowed'), (b'divorced', 'Divorced'), (b'separated', 'Separated'), (b'single', 'Single')], max_length=25, verbose_name='Marital status')),
                ('is_candidate', models.BooleanField(default=False, verbose_name='Candidate')),
            ],
            options={
                'verbose_name': 'Adult',
                'verbose_name_plural': 'Adults',
            },
        ),
    ]
