# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('birthday', models.DateField()),
                ('marital_status', models.CharField(max_length=25)),
                ('is_candidate', models.BooleanField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Address')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Client')),
            ],
            options={
                'verbose_name': 'Adult',
                'verbose_name_plural': 'Adults',
            },
        ),
    ]
