# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('adults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Address'),
        ),
        migrations.AddField(
            model_name='adult',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
    ]
