# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Address'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='is_candidate',
            field=models.BooleanField(default=False),
        ),
    ]
