# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0002_auto_20160513_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adult',
            name='name',
        ),
        migrations.AddField(
            model_name='adult',
            name='first_name',
            field=models.CharField(default='Pepe', max_length=25, verbose_name='First name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adult',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='birthday',
            field=models.DateField(verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='is_candidate',
            field=models.BooleanField(default=False, verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='last_name',
            field=models.CharField(max_length=25, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='marital_status',
            field=models.CharField(max_length=25, verbose_name='Marital status'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Responsable'),
        ),
    ]
