# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0002_auto_20160514_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='birthday',
            field=models.CharField(max_length=20, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='marital_status',
            field=models.CharField(blank=True, choices=[(b'married', 'Married'), (b'widowed', 'Widowed'), (b'divorced', 'Divorced'), (b'separated', 'Separated'), (b'single', 'Single')], max_length=25, null=True, verbose_name='Marital status'),
        ),
    ]
