# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0003_auto_20160527_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('phone', models.CharField(max_length=25, verbose_name='Phone')),
                ('cp', models.CharField(max_length=25, verbose_name='Professional card')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
    ]
