# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0003_auto_20160514_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='marital_status',
            field=models.CharField(choices=[(b'married', 'Married'), (b'widowed', 'Widowed'), (b'divorced', 'Divorced'), (b'separated', 'Separated'), (b'single', 'Single')], max_length=25, verbose_name='Marital status'),
        ),
    ]
