# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0004_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='adult',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adults.Adult', verbose_name='Adult'),
            preserve_default=False,
        ),
    ]
