# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0005_doctor_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='emergency_phone',
            field=models.CharField(default=1, max_length=25, verbose_name='Emergency Phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adult',
            name='phone',
            field=models.CharField(default=1, max_length=25, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
