# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0007_auto_20160621_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Familiar Structure'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='birthday',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='familiar_structure',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Familiar Structure'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='first_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='is_candidate',
            field=models.BooleanField(default=True, verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='last_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='medical_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adults.MedicalInfo', verbose_name='Medical Information'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='personality',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Personality'),
        ),
    ]
