# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0008_auto_20160627_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=25)),
                ('outdoor_number', models.PositiveIntegerField()),
                ('interior_number', models.PositiveIntegerField(blank=True, null=True)),
                ('colony', models.CharField(max_length=25)),
                ('postal_code', models.PositiveIntegerField()),
                ('municipality', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('reference', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.AlterField(
            model_name='adult',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adults.AdultAddress', verbose_name='Address'),
        ),
    ]
