# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0009_auto_20160627_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
    ]
