# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0009_auto_20160627_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='medical_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adults.MedicalInfo', verbose_name='Medical Information'),
        ),
    ]
