# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0010_auto_20160701_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'emma_profile_pictures', verbose_name='Profile picture'),
        ),
    ]
