# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0012_adulthobbies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdultHobbies',
            new_name='AdultHobbie',
        ),
    ]
