# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0013_auto_20160703_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='exercise_pda',
            field=models.BooleanField(default=False, verbose_name='Exercise PDA'),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='knows_pda',
            field=models.BooleanField(default=False, verbose_name='Knows PDA'),
        ),
    ]
