# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0014_auto_20160703_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Description'),
        ),
    ]
