# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0015_auto_20160713_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultaddress',
            name='interior_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='adultaddress',
            name='outdoor_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='adulthobbie',
            name='hobbie',
            field=models.TextField(verbose_name='Hobbie'),
        ),
    ]
