# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0016_auto_20160713_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='familiar_structure',
            field=models.TextField(blank=True, null=True, verbose_name='Familiar Structure'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='personality',
            field=models.TextField(blank=True, null=True, verbose_name='Personality'),
        ),
    ]
