# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0018_auto_20160716_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinfo',
            name='policy_number',
            field=models.CharField(max_length=25, verbose_name='Policy Number'),
        ),
    ]
