# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0019_auto_20160720_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultaddress',
            name='adult_name',
            field=models.CharField(default='asdsa', max_length=40),
            preserve_default=False,
        ),
    ]
