# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-24 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0021_auto_20160723_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adults.AdultAddress', verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adult',
            name='birthday',
            field=models.DateField(default='1997-12-14', verbose_name='Birthday'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adult',
            name='description',
            field=models.TextField(default='asdasdas', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adult',
            name='familiar_structure',
            field=models.TextField(default=1, verbose_name='Familiar Structure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adult',
            name='first_name',
            field=models.CharField(default=1, max_length=25, verbose_name='First name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adult',
            name='last_name',
            field=models.CharField(default=1, max_length=25, verbose_name='Last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adult',
            name='medical_information',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='adults.MedicalInfo', verbose_name='Medical Information'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adult',
            name='personality',
            field=models.TextField(default=1, verbose_name='Personality'),
            preserve_default=False,
        ),
    ]
