# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-24 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0022_auto_20160723_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinfo',
            name='blood_type',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Blood Type'),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='current_medications',
            field=models.TextField(blank=True, null=True, verbose_name='Current Medications'),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='diseases',
            field=models.TextField(blank=True, null=True, verbose_name='Diseases'),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='drug_allergy',
            field=models.TextField(blank=True, null=True, verbose_name='Drug Allergy'),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='food_allergy',
            field=models.TextField(blank=True, null=True, verbose_name='Food Allergy'),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='has_social_security',
            field=models.BooleanField(default=True, verbose_name='Has Social Security'),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='hospital_preferably',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Hospital Preferably'),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='insurance_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Insurance Company'),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='policy_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Policy Experation Date'),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='policy_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Policy Number'),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Social Security Number'),
        ),
    ]
