# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsubscriber',
            name='source',
            field=models.CharField(default='blog', max_length=50, verbose_name='Source'),
            preserve_default=False,
        ),
    ]
