# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254)),
                ('source', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'Potential client',
                'verbose_name_plural': 'Potential clients',
            },
        ),
        migrations.CreateModel(
            name='ScheduledCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Scheduled call',
                'verbose_name_plural': 'Scheduled calls',
            },
        ),
    ]
