# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledcall',
            name='date_time',
            field=models.CharField(max_length=20),
        ),
    ]
