# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20160503_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledcall',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
