# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-24 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number')),
                ('user_type', models.CharField(choices=[(b'User type 1', b'User type 1'), (b'User type 2', b'User type 2'), (b'User type 3', b'User type 3')], max_length=30, verbose_name='User type')),
                ('first_time_dashboard', models.BooleanField(default=True, verbose_name='First time dashboard')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ContractProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_service', models.IntegerField(blank=True, null=True, verbose_name='ID Service')),
                ('workshop_list', models.CharField(blank=True, max_length=50, null=True, verbose_name='Workshop List')),
                ('adult_address_id', models.IntegerField(default=0, verbose_name='ID Adult Address')),
                ('service_setup', models.BooleanField(default=False, verbose_name='Service Setup')),
                ('service_days', models.IntegerField(null=True, verbose_name='Service Days')),
                ('adult_setup', models.BooleanField(default=False, verbose_name='Adult Setup')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='PotentialClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('source', models.CharField(max_length=55, verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Potential client',
                'verbose_name_plural': 'Potential clients',
            },
        ),
    ]
