# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_potentialclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialclient',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='source',
            field=models.CharField(max_length=55, verbose_name='Source'),
        ),
    ]
