# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_contractprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractprocess',
            name='adult_address_id',
            field=models.IntegerField(default=0, verbose_name='ID Adult Address'),
        ),
        migrations.AddField(
            model_name='contractprocess',
            name='service_days',
            field=models.IntegerField(null=True, verbose_name='Service Days'),
        ),
        migrations.AddField(
            model_name='contractprocess',
            name='service_setup',
            field=models.BooleanField(default=False, verbose_name='Service Setup'),
        ),
    ]
