# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20160627_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractprocess',
            name='adult_setup',
            field=models.BooleanField(default=False, verbose_name='Adult Setup'),
        ),
    ]
