# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_contractprocess_adult_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number'),
        ),
    ]
