# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_time_dashboard',
            field=models.BooleanField(default=True, verbose_name='First time dashboard'),
        ),
    ]
