# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_contact_numer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contact_numer',
            new_name='contact_number',
        ),
    ]
