# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_first_time_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='change_password',
        ),
    ]
