# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_client_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='active_client',
        ),
        migrations.AddField(
            model_name='client',
            name='user_type',
            field=models.CharField(choices=[(b'User type 1', b'User type 1'), (b'User type 2', b'User type 2'), (b'User type 3', b'User type 3')], default='User type 1', max_length=30, verbose_name='User type'),
            preserve_default=False,
        ),
    ]
