# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-24 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='First name')),
                ('last_name', models.CharField(max_length=25, verbose_name='Last name')),
                ('cell_phone', models.CharField(max_length=25, verbose_name='Cell Phone')),
                ('home_phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Home Phone')),
                ('working_institution', models.CharField(blank=True, max_length=25, null=True, verbose_name='Working Institution')),
                ('professional_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Professional ID')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
    ]
