# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adults', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiredService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_week', models.PositiveSmallIntegerField(verbose_name='Hours per week')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('reference', models.CharField(max_length=25, verbose_name='Reference')),
                ('frequency', models.CharField(max_length=25, verbose_name='Frecuency')),
                ('adult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adults.Adult', verbose_name='Adult')),
            ],
            options={
                'verbose_name': 'Hired service',
                'verbose_name_plural': 'Hired services',
            },
        ),
        migrations.CreateModel(
            name='ScheduledCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('date_time', models.CharField(max_length=20, verbose_name='Date and time')),
                ('number', models.BigIntegerField(verbose_name='Number')),
            ],
            options={
                'verbose_name': 'Scheduled call',
                'verbose_name_plural': 'Scheduled calls',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'Workshops',
            },
        ),
    ]
