# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('emmas', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiredservice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='emma_alternate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emma_alternate', to='emmas.Emma', verbose_name='Alternative Emma'),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='emma_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emma_assigned', to='emmas.Emma', verbose_name='Emma assigned'),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='emma_cordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cordinator', to='emmas.Emma', verbose_name='Cordinator'),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service', verbose_name='Hired Service'),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Workshop', verbose_name='Workshop'),
        ),
    ]
