# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20160514_0114'),
        ('adults', '0004_auto_20160514_0109'),
        ('emmas', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiredservice',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='hiredservice',
            name='user',
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='adult',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adults.Adult', verbose_name='Adult'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='emma_cordinator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cordinator', to='emmas.Emma', verbose_name='Cordinator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='emma_alternate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emma_alternate', to='emmas.Emma', verbose_name='Alternative Emma'),
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='emma_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emma_assigned', to='emmas.Emma', verbose_name='Emma assigned'),
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='frequency',
            field=models.CharField(max_length=25, verbose_name='Frecuency'),
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='hours_per_week',
            field=models.PositiveSmallIntegerField(verbose_name='Hours per week'),
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='reference',
            field=models.CharField(max_length=25, verbose_name='Reference date'),
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service', verbose_name='Hired Service'),
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Workshop', verbose_name='Workshop'),
        ),
        migrations.AlterField(
            model_name='scheduledcall',
            name='date_time',
            field=models.CharField(max_length=20, verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='scheduledcall',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='scheduledcall',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='scheduledcall',
            name='number',
            field=models.BigIntegerField(verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service', verbose_name='Service'),
        ),
    ]
