# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-24 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('emmas', '0001_initial'),
        ('adults', '0002_adult_responsable'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContractProcess',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.Client', verbose_name='Client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
            options={
                'verbose_name': 'Service contract process',
                'verbose_name_plural': 'Service contract process',
            },
        ),
        migrations.CreateModel(
            name='ServiceDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(b'monday', b'Lunes'), (b'tuesday', b'Martes'), (b'wednesday', b'Miercoles'), (b'thurday', b'Jueves'), (b'friday', b'Viernes'), (b'saturday', b'Sabado'), (b'sunday', b'Domingo')], default=b'', max_length=30)),
                ('start_time', models.CharField(default=b'', max_length=30)),
                ('duration', models.IntegerField(default=1)),
                ('object_id', models.PositiveIntegerField(null=True, verbose_name='Activity or workshop ID')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Workshop or Activity')),
            ],
            options={
                'verbose_name': 'Service Days',
                'verbose_name_plural': 'Service Days',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'Workshops',
            },
        ),
        migrations.AddField(
            model_name='servicecontractprocess',
            name='service_days',
            field=models.ManyToManyField(to='services.ServiceDay'),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='adult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adults.Adult', verbose_name='Adult'),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='emma_alternate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emma_alternate', to='emmas.Emma', verbose_name='Alternative Emma'),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='emma_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emma_assigned', to='emmas.Emma', verbose_name='Emma assigned'),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='emma_cordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cordinator', to='emmas.EmmaCoordinator', verbose_name='Cordinator'),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='workshops',
            field=models.ManyToManyField(to='services.Workshop', verbose_name='Workshops'),
        ),
    ]
