# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20160513_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date_time', models.CharField(max_length=20)),
                ('number', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Scheduled call',
                'verbose_name_plural': 'Scheduled calls',
            },
        ),
    ]
