# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20160924_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecontractprocess',
            name='emma_type',
            field=models.CharField(blank=True, choices=[(b'emma', b'Emma'), (b'frank', b'Frank')], max_length=30, null=True, verbose_name='Gender preference'),
        ),
    ]
