# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-24 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicecontractprocess_emma_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecontractprocess',
            name='certifications',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Certifications'),
        ),
        migrations.AddField(
            model_name='servicecontractprocess',
            name='knowledges',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Knowledges'),
        ),
        migrations.AddField(
            model_name='servicecontractprocess',
            name='languages',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Languages'),
        ),
        migrations.AddField(
            model_name='servicecontractprocess',
            name='skills',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='servicecontractprocess',
            name='emma_type',
            field=models.CharField(blank=True, choices=[(b'emma', b'Emma'), (b'frank', b'Frank')], max_length=30, null=True, verbose_name='Emma preference'),
        ),
    ]
