# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20160515_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiredservice',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='hiredservice',
            name='hours_per_week',
        ),
        migrations.RemoveField(
            model_name='hiredservice',
            name='workshop',
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='num_workshops',
            field=models.IntegerField(default=1, verbose_name='Number of Workshops'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='service_day_1',
            field=models.CharField(default=1, max_length=25, verbose_name='Day 1 of service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='service_day_2',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Day 2 of service'),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='service_day_3',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Day 3 of service'),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='service_day_4',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Day 4 of service'),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='service_day_5',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Day 5 of service'),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='service_day_6',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Day 6 of service'),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='service_day_7',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Day 7 of service'),
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='workshops',
            field=models.CharField(default=1, max_length=100, verbose_name='Workshops'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='adult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adults.Adult', verbose_name='Adult'),
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='emma_alternate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emma_alternate', to='emmas.Emma', verbose_name='Alternative Emma'),
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='emma_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emma_assigned', to='emmas.Emma', verbose_name='Emma assigned'),
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='emma_cordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cordinator', to='emmas.Emma', verbose_name='Cordinator'),
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='start_date',
            field=models.CharField(max_length=25, verbose_name='Start date'),
        ),
    ]
