# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-25 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20160924_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontractprocess',
            name='certifications',
            field=models.TextField(blank=True, null=True, verbose_name='Certifications'),
        ),
        migrations.AlterField(
            model_name='servicecontractprocess',
            name='knowledges',
            field=models.TextField(blank=True, null=True, verbose_name='Knowledges'),
        ),
        migrations.AlterField(
            model_name='servicecontractprocess',
            name='languages',
            field=models.TextField(blank=True, null=True, verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='servicecontractprocess',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Skills'),
        ),
    ]
