# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20160527_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiredservice',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
