# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_hiredservice_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_day_1', models.CharField(max_length=25, verbose_name='Day 1 of service')),
                ('service_day_2', models.CharField(blank=True, max_length=25, null=True, verbose_name='Day 2 of service')),
                ('service_day_3', models.CharField(blank=True, max_length=25, null=True, verbose_name='Day 3 of service')),
                ('service_day_4', models.CharField(blank=True, max_length=25, null=True, verbose_name='Day 4 of service')),
                ('service_day_5', models.CharField(blank=True, max_length=25, null=True, verbose_name='Day 5 of service')),
                ('service_day_6', models.CharField(blank=True, max_length=25, null=True, verbose_name='Day 6 of service')),
                ('service_day_7', models.CharField(blank=True, max_length=25, null=True, verbose_name='Day 7 of service')),
            ],
        ),
        migrations.RemoveField(
            model_name='hiredservice',
            name='service_day_1',
        ),
        migrations.RemoveField(
            model_name='hiredservice',
            name='service_day_2',
        ),
        migrations.RemoveField(
            model_name='hiredservice',
            name='service_day_3',
        ),
        migrations.RemoveField(
            model_name='hiredservice',
            name='service_day_4',
        ),
        migrations.RemoveField(
            model_name='hiredservice',
            name='service_day_5',
        ),
        migrations.RemoveField(
            model_name='hiredservice',
            name='service_day_6',
        ),
        migrations.RemoveField(
            model_name='hiredservice',
            name='service_day_7',
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='service_days',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.ServiceDays', verbose_name='Cordinator'),
            preserve_default=False,
        ),
    ]
