# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-26 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20160924_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecontractprocess',
            name='service_days',
        ),
    ]
