# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20160620_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicedays',
            options={'verbose_name': 'Service Days', 'verbose_name_plural': 'Service Days'},
        ),
        migrations.AddField(
            model_name='servicedays',
            name='name',
            field=models.CharField(default=1, max_length=35, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='service_days',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceDays', verbose_name='Service Days'),
        ),
    ]
