# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20160626_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiredservice',
            name='active',
        ),
        migrations.RemoveField(
            model_name='hiredservice',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='hiredservice',
            name='num_workshops',
        ),
        migrations.RemoveField(
            model_name='hiredservice',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='hiredservice',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='service_days',
            field=models.TextField(verbose_name='Service Days'),
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='workshops',
            field=models.TextField(verbose_name='Workshops'),
        ),
    ]
