# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-30 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0008_serviceday_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('day', models.CharField(blank=True, max_length=30, null=True, verbose_name='Day')),
                ('month', models.CharField(blank=True, max_length=30, null=True, verbose_name='Month')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street')),
                ('num_ext', models.CharField(blank=True, max_length=30, null=True, verbose_name='Num. Ext.')),
                ('num_int', models.CharField(blank=True, max_length=30, null=True, verbose_name='Num. Int.')),
                ('colony', models.CharField(blank=True, max_length=100, null=True, verbose_name='Colony')),
                ('delegation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Delegation')),
                ('cp', models.CharField(blank=True, max_length=30, null=True, verbose_name='Postal Code')),
                ('time', models.CharField(blank=True, max_length=30, null=True, verbose_name='Street')),
                ('duration', models.CharField(blank=True, max_length=30, null=True, verbose_name='Street')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Client')),
            ],
        ),
    ]
