# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-16 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_uniqueservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueservice',
            name='duration',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='uniqueservice',
            name='time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Time'),
        ),
    ]
