# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20160720_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Plans'},
        ),
        migrations.AlterField(
            model_name='hiredservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service', verbose_name='Plan'),
        ),
    ]
