# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20160808_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='service',
        ),
    ]
