# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_remove_workshop_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiredservice',
            name='emma_cordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cordinator', to='emmas.EmmaCoordinator', verbose_name='Cordinator'),
        ),
    ]
