# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20160716_2314'),
        ('services', '0013_auto_20160902_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContractProcess',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.Client', verbose_name='Client')),
                ('plan', models.CharField(blank=True, choices=[(b'basic', b'Basico'), (b'introductory', b'Introductorio'), (b'pro', b'Pro')], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Service contract process',
                'verbose_name_plural': 'Service contract process',
            },
        ),
    ]
