# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_servicecontractprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontractprocess',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
            preserve_default=False,
        ),
    ]
