# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20160922_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='max_weekly_sessions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='weekly_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
