# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-23 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20160922_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='allows_activities',
            field=models.BooleanField(default=False, verbose_name='Allows activities'),
        ),
        migrations.AddField(
            model_name='service',
            name='allows_workshops',
            field=models.BooleanField(default=False, verbose_name='Allows workshops'),
        ),
    ]
