# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-24 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('services', '0018_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedays',
            name='name',
        ),
        migrations.RemoveField(
            model_name='servicedays',
            name='service_day_1',
        ),
        migrations.RemoveField(
            model_name='servicedays',
            name='service_day_2',
        ),
        migrations.RemoveField(
            model_name='servicedays',
            name='service_day_3',
        ),
        migrations.RemoveField(
            model_name='servicedays',
            name='service_day_4',
        ),
        migrations.RemoveField(
            model_name='servicedays',
            name='service_day_5',
        ),
        migrations.RemoveField(
            model_name='servicedays',
            name='service_day_6',
        ),
        migrations.RemoveField(
            model_name='servicedays',
            name='service_day_7',
        ),
        migrations.AddField(
            model_name='servicedays',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Workshop or Activity'),
        ),
        migrations.AddField(
            model_name='servicedays',
            name='day',
            field=models.CharField(choices=[(b'monday', b'Lunes'), (b'tuesday', b'Martes'), (b'wednesday', b'Miercoles'), (b'thurday', b'Jueves'), (b'friday', b'Viernes'), (b'saturday', b'Sabado'), (b'sunday', b'Domingo')], default=b'', max_length=30),
        ),
        migrations.AddField(
            model_name='servicedays',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='servicedays',
            name='object_id',
            field=models.PositiveIntegerField(null=True, verbose_name='related object'),
        ),
        migrations.AddField(
            model_name='servicedays',
            name='start_time',
            field=models.CharField(default=b'', max_length=30),
        ),
    ]
