# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-24 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('services', '0019_auto_20160923_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(b'monday', b'Lunes'), (b'tuesday', b'Martes'), (b'wednesday', b'Miercoles'), (b'thurday', b'Jueves'), (b'friday', b'Viernes'), (b'saturday', b'Sabado'), (b'sunday', b'Domingo')], default=b'', max_length=30)),
                ('start_time', models.CharField(default=b'', max_length=30)),
                ('duration', models.IntegerField(default=1)),
                ('object_id', models.PositiveIntegerField(null=True, verbose_name='Activity or workshop ID')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Workshop or Activity')),
            ],
            options={
                'verbose_name': 'Service Days',
                'verbose_name_plural': 'Service Days',
            },
        ),
        migrations.RemoveField(
            model_name='servicedays',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='ServiceDays',
        ),
        migrations.AddField(
            model_name='servicecontractprocess',
            name='service_days',
            field=models.ManyToManyField(to='services.ServiceDay'),
        ),
    ]
