# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-24 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20160924_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='max_hours_per_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Max hours per month'),
        ),
    ]
