# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('movile_phone', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
                ('school_grade', models.CharField(max_length=15)),
                ('how_met_emma', models.CharField(max_length=15)),
                ('has_facebook', models.BooleanField()),
                ('has_smathphone', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emma',
                'verbose_name_plural': 'Emmas',
            },
        ),
    ]
