# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_cooluser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emma',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('movile_phone', models.PositiveIntegerField(verbose_name='Movile phone')),
                ('phone', models.PositiveIntegerField(verbose_name='Phone')),
                ('school_grade', models.CharField(max_length=15, verbose_name='School grade')),
                ('how_met_emma', models.CharField(max_length=15, verbose_name='How met Emma')),
                ('has_facebook', models.BooleanField(default=False, verbose_name='Has Facebook')),
                ('has_smathphone', models.BooleanField(default=False, verbose_name='Has smathphone')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Address', verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Emma',
                'verbose_name_plural': 'Emmas',
            },
        ),
    ]
