# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('emmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emma',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Address'),
            preserve_default=False,
        ),
    ]
