# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialEmma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=25, verbose_name='Last Name')),
                ('age', models.CharField(max_length=10, verbose_name='Age')),
                ('movile_phone', models.PositiveIntegerField(verbose_name='Movile phone')),
                ('phone', models.PositiveIntegerField(verbose_name='Phone')),
                ('school_grade', models.CharField(max_length=15, verbose_name='School grade')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('how_met_emma', models.CharField(max_length=15, verbose_name='How met Emma')),
                ('has_facebook', models.BooleanField(default=False, verbose_name='Has Facebook')),
                ('has_smathphone', models.BooleanField(default=False, verbose_name='Has smathphone')),
            ],
            options={
                'verbose_name': 'Potential Emma',
                'verbose_name_plural': 'Potential Emmas',
            },
        ),
        migrations.AlterModelOptions(
            name='emma',
            options={},
        ),
        migrations.RemoveField(
            model_name='emma',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='emma',
            name='has_facebook',
        ),
        migrations.RemoveField(
            model_name='emma',
            name='has_smathphone',
        ),
        migrations.RemoveField(
            model_name='emma',
            name='how_met_emma',
        ),
        migrations.RemoveField(
            model_name='emma',
            name='movile_phone',
        ),
        migrations.RemoveField(
            model_name='emma',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='emma',
            name='school_grade',
        ),
        migrations.AddField(
            model_name='emma',
            name='characteristics',
            field=models.CharField(default='a', max_length=50, verbose_name='Characteristics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emma',
            name='experience_with_seniors',
            field=models.CharField(default='a', max_length=50, verbose_name='Experience with Seniors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emma',
            name='general_description',
            field=models.CharField(default='a', max_length=30, verbose_name='General Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emma',
            name='main_occupation',
            field=models.CharField(default='a', max_length=30, verbose_name='Main occupation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emma',
            name='qualities',
            field=models.CharField(default='aa', max_length=50, verbose_name='Qualities'),
            preserve_default=False,
        ),
    ]
