# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmas', '0002_emma_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emma',
            name='has_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emma',
            name='has_smathphone',
            field=models.BooleanField(default=False),
        ),
    ]
