# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emmas', '0002_auto_20160620_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emma',
            options={'verbose_name': 'Emma', 'verbose_name_plural': 'Emmas'},
        ),
    ]
