# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emmas', '0003_auto_20160629_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmmaStudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studie', models.CharField(max_length=50, verbose_name='Studie')),
                ('emma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emmas.Emma', verbose_name=b'Emma')),
            ],
            options={
                'verbose_name': 'Emma Studie',
                'verbose_name_plural': 'Emma Studies',
            },
        ),
    ]
