# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmas', '0006_emmahobbie'),
    ]

    operations = [
        migrations.AddField(
            model_name='emma',
            name='profile_picture',
            field=models.ImageField(default='Hola', upload_to=b'profile_pictures'),
            preserve_default=False,
        ),
    ]
