# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmas', '0007_emma_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emma',
            name='characteristics',
            field=models.TextField(max_length=500, verbose_name='Characteristics'),
        ),
        migrations.AlterField(
            model_name='emma',
            name='experience_with_seniors',
            field=models.TextField(max_length=500, verbose_name='Experience with Seniors'),
        ),
        migrations.AlterField(
            model_name='emma',
            name='general_description',
            field=models.TextField(max_length=500, verbose_name='General Description'),
        ),
        migrations.AlterField(
            model_name='emma',
            name='qualities',
            field=models.TextField(max_length=500, verbose_name='Qualities'),
        ),
        migrations.AlterField(
            model_name='emmahobbie',
            name='hobbie',
            field=models.TextField(max_length=200, verbose_name='Hobbie'),
        ),
    ]
