# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-23 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmas', '0008_auto_20160630_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='emma',
            name='phone',
            field=models.CharField(default=5539119192, max_length=30, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
