# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-24 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmas', '0009_emma_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emma',
            name='main_occupation',
            field=models.TextField(verbose_name='Main occupation'),
        ),
    ]
