# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmas', '0010_auto_20160724_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialemma',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
    ]
