# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmas', '0011_auto_20160812_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialemma',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
    ]
