# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmas', '0012_auto_20160812_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialemma',
            name='age',
            field=models.CharField(max_length=100, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='potentialemma',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='potentialemma',
            name='how_met_emma',
            field=models.CharField(max_length=100, verbose_name='How met Emma'),
        ),
        migrations.AlterField(
            model_name='potentialemma',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='potentialemma',
            name='movile_phone',
            field=models.CharField(max_length=100, verbose_name='Movile phone'),
        ),
        migrations.AlterField(
            model_name='potentialemma',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='potentialemma',
            name='school_grade',
            field=models.CharField(max_length=100, verbose_name='School grade'),
        ),
    ]
