# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160723_1303'),
        ('emmas', '0013_auto_20160816_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmmaCoordinator',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to=b'profile_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
            ],
        ),
    ]
