# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmas', '0013_auto_20160816_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emma',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='emma',
            name='characteristics',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Characteristics'),
        ),
        migrations.AlterField(
            model_name='emma',
            name='experience_with_seniors',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Experience with Seniors'),
        ),
        migrations.AlterField(
            model_name='emma',
            name='general_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='General Description'),
        ),
        migrations.AlterField(
            model_name='emma',
            name='main_occupation',
            field=models.TextField(blank=True, null=True, verbose_name='Main occupation'),
        ),
        migrations.AlterField(
            model_name='emma',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='emma',
            name='qualities',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Qualities'),
        ),
    ]
