# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emmas', '0014_emmacordinator'),
        ('emmas', '0014_auto_20160818_2148'),
    ]

    operations = [
    ]
