# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(max_length=100000)),
                ('status', models.CharField(max_length=25)),
                ('descripcion', models.TextField(max_length=30)),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('movement', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
            },
        ),
        migrations.CreateModel(
            name='Suscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_customer', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Suscription',
                'verbose_name_plural': 'Suscriptions',
            },
        ),
    ]
