# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_potentialclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(max_length=100000)),
                ('status', models.CharField(max_length=25)),
                ('descripcion', models.TextField(max_length=30)),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('movement', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
            },
        ),
        migrations.CreateModel(
            name='Suscription',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('id_customer', models.CharField(max_length=25, verbose_name='Cuatomer ID')),
                ('status', models.CharField(max_length=25, verbose_name='Status')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscriptions', to='clients.Client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Suscription',
                'verbose_name_plural': 'Suscriptions',
            },
        ),
        migrations.AddField(
            model_name='history',
            name='suscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='suscriptions.Suscription'),
        ),
        migrations.AddField(
            model_name='charge',
            name='suscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='suscriptions.Suscription'),
        ),
    ]
