# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('suscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscriptions', to='clients.Client'),
        ),
        migrations.AddField(
            model_name='history',
            name='suscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='suscriptions.Suscription'),
        ),
        migrations.AddField(
            model_name='charge',
            name='suscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='suscriptions.Suscription'),
        ),
    ]
