# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-24 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('suscriptions', '0001_initial'),
        ('services', '0002_auto_20160924_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscription',
            fields=[
                ('id', models.BigIntegerField(verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='suscriptions', serialize=False, to='clients.Client', verbose_name='Client')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('openpay_id', models.CharField(max_length=25, verbose_name='Openpay ID')),
                ('status', models.CharField(max_length=25, verbose_name='Status')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Suscription',
                'verbose_name_plural': 'Suscriptions',
            },
        ),
        migrations.AddField(
            model_name='history',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service', verbose_name=b'Service'),
        ),
        migrations.AddField(
            model_name='history',
            name='suscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='suscriptions.Suscription', verbose_name='Suscription'),
        ),
        migrations.AddField(
            model_name='history',
            name='workshops',
            field=models.ManyToManyField(to='services.Workshop', verbose_name='Workshops'),
        ),
        migrations.AddField(
            model_name='charge',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='services.Service', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='charge',
            name='suscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='suscriptions.Suscription', verbose_name='Suscription'),
        ),
    ]
