# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='amount',
            field=models.FloatField(max_length=100000),
        ),
    ]
