# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-25 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscriptions', '0002_auto_20160924_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=b'charges_files', verbose_name='File'),
        ),
    ]
