# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscriptions', '0002_auto_20160514_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscription',
            name='id',
            field=models.BigIntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='suscription',
            name='openpay_id',
            field=models.CharField(max_length=25, verbose_name='Openpay ID'),
        ),
    ]
