# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscriptions', '0002_auto_20160503_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='movement',
            field=models.CharField(max_length=200),
        ),
    ]
