# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20160720_2012'),
        ('suscriptions', '0003_auto_20160716_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='movement',
        ),
        migrations.AddField(
            model_name='history',
            name='comments',
            field=models.TextField(default=1, verbose_name='Comments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='mood',
            field=models.CharField(default=1, max_length=130, verbose_name='Mood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.Service', verbose_name=b'Service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='workshops',
            field=models.ManyToManyField(to='services.Workshop', verbose_name='Workshops'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(verbose_name='Creation date'),
        ),
    ]
