# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscriptions', '0004_auto_20160721_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(verbose_name='Creation date'),
        ),
    ]
