# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-24 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import emma.apps.suscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('suscriptions', '0005_auto_20160721_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='file',
            field=models.FileField(default='file', upload_to=emma.apps.suscriptions.models.get_file_path, verbose_name='File'),
            preserve_default=False,
        ),
    ]
