# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import emma.apps.suscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('suscriptions', '0006_history_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=emma.apps.suscriptions.models.get_file_path, verbose_name='File'),
        ),
    ]
