# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscriptions', '0007_auto_20160906_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=b'reports', verbose_name='File'),
        ),
    ]
