# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20160902_1646'),
        ('suscriptions', '0009_auto_20160915_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='charge',
            name='card',
            field=models.CharField(default='3333XXXX33333', max_length=25, verbose_name='Card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='file',
            field=models.FileField(default='file', upload_to=b'reports', verbose_name='File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='services.Service', verbose_name='Plan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charge',
            name='status',
            field=models.CharField(choices=[(b'paid', b'Paid'), (b'pending', b'Pending')], max_length=25, verbose_name='Status'),
        ),
    ]
