# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooluser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='staff status'),
        ),
    ]
