# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160513_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id',
            field=models.BigIntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
