# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_client_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='active_client',
            field=models.BooleanField(default=False),
        ),
    ]
