# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160527_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='interior_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='outdoor_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.PositiveIntegerField(),
        ),
    ]
