# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160531_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooluser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='cooluser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
    ]
