# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 17:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160531_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooluser',
            name='join_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 6, 17, 17, 20, 29, 795933, tzinfo=utc), verbose_name='Join Date'),
            preserve_default=False,
        ),
    ]
