# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_address'),
        ('adults', '0009_auto_20160627_1050'),
        ('users', '0006_cooluser_join_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
