# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-23 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160627_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooluser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='cooluser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='cooluser',
            name='father_last_name',
            field=models.CharField(default='Mejia', max_length=30, verbose_name='Father last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooluser',
            name='mother_last_name',
            field=models.CharField(default='Ramirez', max_length=30, verbose_name='Mother last name'),
            preserve_default=False,
        ),
    ]
